#pragma once
#include <autoconf.h>

#define KRNLSYMTABLE_MKMIEXECKRNLFUNC 0x00
#define KRNLSYMTABLE_MKMIREGISTERMODL 0x01
#define KRNLSYMTABLE_MKMIUNREGISTMODL 0x02
#define KRNLSYMTABLE_MKMIGETMODULE    0x03
#define KRNLSYMTABLE_MKMIBUFFERCREATE 0x04
#define KRNLSYMTABLE_MKMIBUFFERIOCTL  0x05
#define KRNLSYMTABLE_MKMIBUFFERDELETE 0x06
