#pragma once
#include <autoconf.h>

#if defined(__x86_64__)
#define ARCH_x64
#elif defined(__aarch64__)
#define ARCH_aarch64
#else
#error Unsupported architecture
#endif

#if !defined(MODULE_NAME)
	#define MODULE_NAME "Generic"
#endif

#define HIGHER_HALF 0xFFFF800000000000

#define SHORTEST_STRING_LENGTH 			16
#define SHORTER_STRING_LENGTH			32
#define SHORT_STRING_LENGTH			64
#define MEDIUM_STRING_LENGTH			128
#define LONGER_STRING_LENGTH			256
#define LONG_STRING_LENGTH			512
#define VERY_LONG_STRING_LENGTH			1024
#define PAGE_STRING_LENGTH			4096

#define MAX_KERNEL_MODULE_NAME_LENGTH SHORTEST_STRING_LENGTH
#define MAX_FILE_NAME_LENGTH LONGER_STRING_LENGTH
#define MAX_CMDLINE_ARGUMENT_LENGTH LONG_STRING_LENGTH
#define MAX_CMDLINE_LENGTH VERY_LONG_STRING_LENGTH
#define MAX_SYMBOL_LENGTH SHORT_STRING_LENGTH
#define MAX_SECTION_LENGTH SHORTER_STRING_LENGTH

#define MAX_PRINTK_MESSAGE_LENGTH VERY_LONG_STRING_LENGTH
#define MAX_PRINTK_SYSCALL_MESSAGE_LENGTH VERY_LONG_STRING_LENGTH

#define MEMORY_MASK_TYPE    0b00000111
#define MEMORY_SYSGENERAL   0b00000001
#define MEMORY_SYSIO        0b00000010

#define MEMORY_MASK_SIZE    0b00111000
#define MEMORY_ACCESS_BYTE  0b00001000
#define MEMORY_ACCESS_WORD  0b00010000
#define MEMORY_ACCESS_DWORD 0b00011000
#define MEMORY_ACCESS_QWORD 0b00100000

#define MEMORY_MASK_ACCESS  0b11000000
#define MEMORY_ACCESS_READ  0b01000000
#define MEMORY_ACCESS_WRITE 0b10000000

typedef enum {
	SYSCALL_VECTOR_START = 0,
	SYSCALL_DEBUG_PRINTK = 1,
	SYSCALL_MEMORY_VMALLOC = 3,
	SYSCALL_MEMORY_PMALLOC = 4,
	SYSCALL_MEMORY_VMFREE = 5,
	SYSCALL_MEMORY_MMAP = 6,
	SYSCALL_MEMORY_UNMAP = 7,
	SYSCALL_MEMORY_INOUT = 8,
	SYSCALL_PROC_EXEC = 9,
	SYSCALL_PROC_FORK = 10,
	SYSCALL_PROC_RETURN = 11,
	SYSCALL_PROC_EXIT = 12,
	SYSCALL_PROC_WAIT = 13,
	SYSCALL_PROC_KILL = 14,
	SYSCALL_MODULE_REGISTER	= 15,
	SYSCALL_MODULE_UNREGISTER = 16,
	SYSCALL_MODULE_BUFFER_CREATE = 17,
	SYSCALL_MODULE_BUFFER_MAP = 18,
	SYSCALL_MODULE_BUFFER_UNMAP = 19,
	SYSCALL_MODULE_BUFFER_DELETE = 20,
	SYSCALL_MODULE_MESSAGE_HANDLER = 21,
	SYSCALL_MODULE_MESSAGE_SEND = 22,
	SYSCALL_MODULE_SECTION_REGISTER	= 23,
	SYSCALL_MODULE_SECTION_GET = 24,
	SYSCALL_MODULE_SECTION_UNREGISTER = 25,
	SYSCALL_VECTOR_END = 26
} SyscallVectorNumbers;

#define BUFFER_TYPE_COMMUNICATION_MODULE_KERNEL 0xA000
#define BUFFER_TYPE_LOG_PRINTK                  0xA001
#define BUFFER_TYPE_DATA_MODULE_GENERIC         0xA002
#define BUFFER_TYPE_HW_IO_GENERIC               0xA003

#define BUFFER_OPERATION_READDATA_SYNC          0xB000
#define BUFFER_OPERATION_WRITEDATA_SYNC         0xB001

#define EAGAIN      1
#define EBADREQUEST  2
#define EBUSY       3
#define EFAULT      4
#define EINVALID    5
#define ENOSECTION  6
#define ENODRIVER   7
#define ENODEVICE   8
#define ENOMEMORY   9
#define EPERMISSION 10
#define ENOTPRESENT 11
